version: '3.8'

services:
  fhe-processor:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - fhe-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  fhe-processor-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8502:8501"
      - "8888:8888"  # Jupyter
    volumes:
      - .:/app
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
      - DEVELOPMENT=true
    restart: unless-stopped
    networks:
      - fhe-network
    command: streamlit run fhe_financial_processor.py --server.port=8501 --server.address=0.0.0.0 --server.runOnSave=true

  fhe-processor-openfhe:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-openfhe
    ports:
      - "8503:8501"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
      - OPENFHE_ENABLED=true
    restart: unless-stopped
    networks:
      - fhe-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - fhe-processor
    networks:
      - fhe-network
    restart: unless-stopped

networks:
  fhe-network:
    driver: bridge

volumes:
  fhe-data:
    driver: local
  fhe-uploads:
    driver: local
  fhe-exports:
    driver: local
  fhe-logs:
    driver: local